window.IvyTutorBoot({
  tutorName: "IvyEuro AI 中文老师",
  knowledgeBaseUrl: "data/chinese-knowledge-base.json",
  fallbackKnowledgeBase: {
    tutor: {
      name: "IvyEuro AI Chinese Tutor",
      role: "先检索知识库，再组织成识字、朗读、纠错和表达练习的答案。",
      principles: [
        "先找来源，再生成回答",
        "优先使用可朗读、可练习的短句",
        "根据年级和水平调整语气和复杂度",
        "回答后给出下一步练习",
      ],
    },
    sources: [
      { id: "plain-text", name: "Plain text", summary: "可直接导入讲义、课文、练习文本和课堂纠错记录。", focus: "自定义内容、课堂文本、练习材料", keywords: ["自定义", "讲义", "练习", "文本", "纠错", "课堂", "课文", "读写"] },
      { id: "textbook", name: "部编版语文教材", summary: "适合学校同步、基础积累和分阶段训练。", focus: "课内同步、基础积累、阶段训练", keywords: ["教材", "课文", "同步", "语文", "拼音", "识字", "朗读", "字词"] },
      { id: "reading", name: "课外阅读", summary: "适合阅读理解、段落分析和词句拓展。", focus: "阅读理解、段落分析、词句拓展", keywords: ["阅读", "理解", "段落", "词句", "拓展", "故事", "文章"] },
      { id: "pinyin", name: "拼音朗读材料", summary: "适合读音、停顿和语感训练。", focus: "拼音、朗读、节奏", keywords: ["拼音", "朗读", "读音", "停顿", "语感", "发音"] },
      { id: "writing", name: "作文范文", summary: "适合结构、表达和润色示范。", focus: "结构、表达、润色", keywords: ["作文", "范文", "表达", "结构", "润色", "写作"] },
    ],
    modes: [
      { id: "plain-text", label: "Plain text", title: "导入文本", summary: "把课文、讲义和练习变成可直接讲解的内容。", promptHint: "适合上传讲义、课文、练习或自定义文本。", preferredSources: ["plain-text"], sampleQuestions: ["把这段课文整理成课堂要点", "把这份练习变成三步练习", "把这篇文章总结成 5 个重点"], outputStyle: "摘要 + 可讲解要点 + 下一步" },
      { id: "dialogue", label: "对话", title: "情景对话", summary: "围绕校园、生活和日常场景进行问答与追问。", promptHint: "适合练习口头表达和完整句输出。", preferredSources: ["textbook", "plain-text"], sampleQuestions: ["请和学生做一个校园问答", "请模拟老师和学生的自我介绍", "请练习一个去图书馆的对话"], outputStyle: "对白 + 追问 + 复述" },
      { id: "correction", label: "纠错", title: "病句纠错", summary: "把学生输入修正成更自然、更准确的中文。", promptHint: "适合批改病句、语序和用词问题。", preferredSources: ["textbook", "plain-text"], sampleQuestions: ["这句话有病句，帮我纠正", "我昨天去公园玩和朋友，帮我改", "这句表达不顺，帮我润色"], outputStyle: "原句 + 修改句 + 错误说明" },
      { id: "pronunciation", label: "发音", title: "拼音与朗读", summary: "聚焦拼音、声调、停顿和语感。", promptHint: "适合练拼音、朗读和句子节奏。", preferredSources: ["pinyin", "textbook"], sampleQuestions: ["请示范这句话的拼音和停顿", "我想练‘我们一起去公园’的朗读", "请帮我纠正这句的声调"], outputStyle: "拼音提示 + 停顿建议 + 跟读句" },
      { id: "essay", label: "作文", title: "写作批改", summary: "从立意、结构、连接到完整段落输出。", promptHint: "适合写段落、写短文、做作文提纲和润色。", preferredSources: ["writing", "plain-text"], sampleQuestions: ["写一段关于学校生活的作文", "帮我把这篇作文改得更有逻辑", "给我一个关于旅行的段落提纲"], outputStyle: "提纲 + 示例段落 + 连接词" },
      { id: "reading", label: "阅读", title: "阅读理解", summary: "帮助学生抓主旨、找细节、理解词句关系。", promptHint: "适合阅读理解、词句拓展和短文分析。", preferredSources: ["reading", "textbook"], sampleQuestions: ["帮我分析这篇阅读的主旨", "这篇文章里有哪些关键词", "给我一个阅读理解训练"], outputStyle: "主旨 + 关键词 + 题目" },
    ],
    demoQuestions: ["怎么帮小学二年级学生练识字和朗读？", "这句话有病句，帮我纠正", "怎样把学校里的语文课文和课后练习串起来？"],
  },
  selectors: {
    questionField: "#chinese-ai-question",
    answerBox: "#chinese-ai-answer",
    sourceRow: "#chinese-ai-sources",
    kbList: "#chinese-kb-list",
    askButton: "[data-chinese-ask]",
    resetButton: "[data-chinese-reset]",
    activeModeName: "#chinese-active-mode-title",
    activeModeHint: "#chinese-active-mode-hint",
    modeButtons: "[data-chinese-mode]",
    functionCards: "[data-tutor-card]",
  },
  modeAttr: "data-chinese-mode",
  sampleAttr: "data-chinese-sample",
  sampleSelector: "[data-chinese-sample]",
  defaultModeId: "dialogue",
  defaultQuestion: "怎么帮学生练中文？",
  defaultFocus: "先用知识库中的标准文本示范，再让学生跟读和复练。",
  defaultNextStep: "建议先从一句短句开始，确认发音后再进入问答。",
  defaultExample: "我们一起去公园。",
  defaultExtra: "你可以继续追问：请给我一个更简单的版本。",
  sourceScoring: [
    { pattern: "阅读|读|文章", sourceId: "reading", bonus: 2 },
    { pattern: "拼音|朗读|声调|读音", sourceId: "pinyin", bonus: 2 },
    { pattern: "作文|写作|段落", sourceId: "writing", bonus: 2 },
    { pattern: "病句|纠错|修改|语序", sourceId: "textbook", bonus: 2 },
  ],
  modeOverrides: {
    "plain-text": {
      focus: "先把输入文本拆成主题、关键词、示范句和复练任务。",
      nextStep: "先整理成三段：讲解、练习、复习。",
      example: "主题：校园生活；关键词：认真、练习、朗读。",
      extra: "你可以继续追问：把这段讲义变成 3 个课堂任务。",
    },
    dialogue: {
      focus: "先给学生完整对话框架，再让他按角色接话和追问。",
      nextStep: "先练两轮问答，再切换场景继续。",
      example: "A: 你今天学了什么？ B: 我学了识字和朗读。",
      extra: "你可以继续追问：再给我一个更适合小学生的对话。",
    },
    correction: {
      focus: "先展示修改后的正确句，再解释错误点。",
      nextStep: "让学生把改正句重复说一遍，确认掌握。",
      example: "我昨天去公园和朋友玩。",
      extra: "建议一次只改 1 句，方便学生看到前后差异。",
      modeLabelLine: "当前功能：纠错 · 已识别到一句需要纠正的句子",
    },
    pronunciation: {
      focus: "先拆分拼音、声调和停顿，再提供朗读提示。",
      nextStep: "先跟读标准句，再把句子放进短文里练。",
      example: "我们 / 一起 / 去 / 公园。",
      extra: "如果你读得慢一点，系统会先示范，再让你跟读。",
      modeLabelLine: "当前功能：发音 · 优先做拼音与朗读",
    },
    essay: {
      focus: "先给写作提纲，再补连接词和示范段落。",
      nextStep: "先写三句，再扩成一段，再做润色。",
      example: "开头：介绍校园；中间：描述活动；结尾：表达感受。",
      extra: "你可以继续追问：帮我把这一段写得更像作文。",
    },
    reading: {
      focus: "先抓主旨和关键词，再做细节理解与题目训练。",
      nextStep: "先读标题和首尾句，再回答 3 个理解题。",
      example: "主旨：这篇文章讲的是校园里的阅读习惯。",
      extra: "阅读模式会优先给主旨、词句和题目框架。",
      modeLabelLine: "当前功能：阅读 · 优先做主旨和细节理解",
    },
  },
  fallbackMatchers: [
    {
      pattern: "阅读|读|文章",
      targetModeId: "reading",
      focus: "先从短文和词句理解入手，再做段落复述与问题回答。",
      nextStep: "先让学生找关键词，再用完整句子回答问题。",
      example: "这篇文章讲的是校园生活。",
    },
    {
      pattern: "拼音|朗读|声调|读音",
      targetModeId: "pronunciation",
      focus: "先看标准示范，再做拼音、停顿和语感纠正。",
      nextStep: "先跟读标准句，再把语感和停顿再练一遍。",
      example: "我们一起去公园。",
    },
    {
      pattern: "口语|说|问答",
      targetModeId: "dialogue",
      focus: "先给学生一个完整回答框架，再让他用自己的话说出来。",
      nextStep: "把问题拆成开头句、核心句和结尾句来练。",
      example: "我最喜欢的是语文，因为我喜欢读故事。",
    },
    {
      pattern: "写作|作文",
      targetModeId: "essay",
      focus: "先给写作结构，再补词句和连接词，最后检查完整性。",
      nextStep: "先写三句，再扩成一段，最后润色表达。",
      example: "开头先交代时间和地点，再写经过，最后写感受。",
    },
    {
      pattern: "教材|学校|同步",
      targetModeId: "plain-text",
      focus: "先和学校教材对齐，再把课内词句和课后练习串起来。",
      nextStep: "先确认课本单元，再给学生一个同步练习。",
      example: "这一课重点是识字、朗读和短句表达。",
    },
  ],
});
