window.IvyTutorBoot({
  tutorName: "IvyEuro AI 英语老师",
  fallbackKnowledgeBase: {
    tutor: {
      name: "IvyEuro AI English Tutor",
      role: "先检索知识库，再组织成课堂示范、跟读纠错和追问练习的答案。",
      principles: [
        "先找来源，再生成回答",
        "优先使用可教学、可复练的短句",
        "根据年龄和水平调整语气和复杂度",
        "回答后给出下一步练习",
      ],
    },
    sources: [
      { id: "plain-text", name: "Plain text", summary: "可直接导入自定义课程内容、讲义、练习文本和课堂纠错记录。", focus: "自定义内容、课堂文本、练习材料", keywords: ["自定义", "讲义", "练习", "文本", "纠错", "课堂", "worksheet", "lesson"] },
      { id: "oxford", name: "Oxford", summary: "适合英语阅读、词汇与表达的权威参考，便于构建稳定的词汇和阅读训练。", focus: "词汇、阅读、表达", keywords: ["oxford", "阅读", "词汇", "表达", "reading", "vocabulary", "词组"] },
      { id: "cambridge", name: "Cambridge", summary: "适合分级练习、题型训练和标准化输出，尤其适合测评和阶段提升。", focus: "分级、题型、标准化练习", keywords: ["cambridge", "分级", "题型", "测评", "考试", "标准化", "level", "exam"] },
      { id: "reach-higher", name: "Reach Higher", summary: "适合课堂体系、阅读写作与综合提升，能把知识点串成完整训练路径。", focus: "阅读、写作、综合提升", keywords: ["reach higher", "写作", "阅读", "综合", "提升", "课堂", "writing"] },
      { id: "us-textbook", name: "美国学校教材", summary: "适合本地化英语学习、学校同步与日常表达，便于贴近课堂场景。", focus: "学校同步、日常表达、课堂场景", keywords: ["美国", "学校", "教材", "同步", "课堂", "口语", "日常", "school", "textbook"] },
    ],
    modes: [
      { id: "plain-text", label: "Plain text", title: "导入文本", summary: "把教材、讲义、练习变成可直接讲解和复练的内容。", promptHint: "适合上传讲义、课文、练习或自定义文本，让 AI 先整理再讲解。", preferredSources: ["plain-text"], sampleQuestions: ["把这段讲义整理成课堂要点", "把这份练习变成三步练习", "把这段教材总结成 5 个词汇"], outputStyle: "摘要 + 可讲解要点 + 下一步" },
      { id: "dialogue", label: "对话", title: "情景对话", summary: "围绕课堂、生活和学校场景进行问答与追问。", promptHint: "适合练习问答、角色扮演和完整句输出。", preferredSources: ["us-textbook", "plain-text"], sampleQuestions: ["请和学生做一个校园点餐对话", "请模拟老师和学生的自我介绍", "请练习一个去图书馆的对话"], outputStyle: "角色对白 + 追问 + 复述" },
      { id: "correction", label: "纠错", title: "语法纠错", summary: "把学生输入修正成更自然、更准确的英语。", promptHint: "适合批改句子、找语法问题、改表达。", preferredSources: ["cambridge", "plain-text"], sampleQuestions: ["I go school yesterday. 帮我纠错", "He don't like apples. 帮我改正", "This sentence has grammar mistakes, please fix it"], outputStyle: "原句 + 修改句 + 错误说明" },
      { id: "pronunciation", label: "发音", title: "发音示范", summary: "聚焦音节、重音、连读和语调，让学生听完就能跟。", promptHint: "适合练发音、口型、重音和句子节奏。", preferredSources: ["cambridge", "us-textbook"], sampleQuestions: ["how do you pronounce 'th'?", "请示范 better 和 butter 的区别", "我想练 this, think, these 的发音"], outputStyle: "发音提示 + 口型建议 + 跟读句" },
      { id: "essay", label: "作文", title: "作文批改", summary: "从立意、结构、连接词到完整段落输出。", promptHint: "适合写段落、写短文、做作文提纲和润色。", preferredSources: ["reach-higher", "plain-text"], sampleQuestions: ["写一段关于我学校的英语作文", "帮我把这篇作文改得更有逻辑", "给我一个关于旅行的段落提纲"], outputStyle: "提纲 + 示例段落 + 连接词" },
      { id: "reading", label: "阅读", title: "阅读理解", summary: "帮助学生抓主旨、找细节、理解词汇和句子关系。", promptHint: "适合阅读理解、词汇拓展和短文分析。", preferredSources: ["oxford", "cambridge", "reach-higher"], sampleQuestions: ["帮我分析这篇阅读的主旨", "这篇文章里有哪些关键词", "给我一个阅读理解训练"], outputStyle: "主旨 + 关键词 + 题目" },
    ],
    demoQuestions: ["怎么帮小学三年级学生练英语阅读和口语？", "学生总是发音拖尾，应该怎么纠正？", "怎样把学校里的英语课本和课后练习串起来？"],
  },
  selectors: {
    questionField: "#english-ai-question",
    answerBox: "#english-ai-answer",
    sourceRow: "#english-ai-sources",
    kbList: "#english-kb-list",
    askButton: "[data-english-ai-ask]",
    resetButton: "[data-english-ai-reset]",
    activeModeName: "#english-active-mode strong",
    activeModeHint: "#english-active-mode span",
    modeButtons: "[data-tutor-mode]",
    functionCards: "[data-tutor-card]",
  },
  modeAttr: "data-tutor-mode",
  sampleAttr: "data-sample-query",
  sampleSelector: "[data-sample-query]",
  defaultModeId: "dialogue",
  defaultQuestion: "怎么帮学生练英语阅读和口语？",
  defaultFocus: "先用知识库中的标准文本示范，再让学生跟读和复练。",
  defaultNextStep: "建议先从一句短句开始，确认发音后再进入问答。",
  defaultExample: "Can you say that again?",
  defaultExtra: "你可以继续追问：请给我一个更简单的版本。",
  sourceScoring: [
    { pattern: "阅读|read|reading", sourceId: "oxford", bonus: 2 },
    { pattern: "口语|说|speak|speaking", sourceId: "us-textbook", bonus: 1 },
    { pattern: "发音|pronunciation|跟读|repeat", sourceId: "cambridge", bonus: 2 },
    { pattern: "写作|writing", sourceId: "reach-higher", bonus: 2 },
    { pattern: "课堂|讲义|练习|自定义|worksheet|lesson", sourceId: "plain-text", bonus: 2 },
  ],
  modeOverrides: {
    "plain-text": {
      focus: "先把输入文本拆成主题、关键词、示范句和复练任务。",
      nextStep: "先整理成三段：讲解、练习、复习。",
      example: "Main idea: classroom communication. Keywords: ask, repeat, slow.",
      extra: "你可以继续追问：把这份讲义变成 3 个课堂任务。",
    },
    dialogue: {
      focus: "先给学生完整对话框架，再让他按角色接话和追问。",
      nextStep: "先练两轮问答，再切换场景继续。",
      example: "A: Could I have a glass of water? B: Sure. Here you are.",
      extra: "你可以继续追问：再给我一个更适合小学生的对话。",
    },
    correction: {
      focus: "先展示修改后的正确句，再解释错误点。",
      nextStep: "让学生把改正句重复说一遍，确认掌握。",
      example: "I went to school yesterday.",
      extra: "建议一次只改 1 句，方便学生看到前后差异。",
      modeLabelLine: "当前功能：纠错 · 已识别到一句需要纠正的句子",
    },
    pronunciation: {
      focus: "先拆分音节、重音和连读，再提供口型提示。",
      nextStep: "先跟读单词，再把单词放进句子里练。",
      example: "this /ðɪs/ → 注意舌尖轻触牙齿，声音不要太重。",
      extra: "如果你读得慢一点，系统会先示范，再让你跟读。",
      modeLabelLine: "当前功能：发音 · 优先做单词与短句发音",
    },
    essay: {
      focus: "先给写作提纲，再补连接词和示范段落。",
      nextStep: "先写三句，再扩成一段，再做润色。",
      example: "Outline: topic sentence / two supporting ideas / conclusion.",
      extra: "你可以继续追问：帮我把这一段写得更像考试作文。",
    },
    reading: {
      focus: "先抓主旨和关键词，再做细节理解与题目训练。",
      nextStep: "先读标题和首尾句，再回答 3 个理解题。",
      example: "Main idea: the passage is about daily habits and routines.",
      extra: "阅读模式会优先给主旨、词汇和题目框架。",
      modeLabelLine: "当前功能：阅读 · 优先做主旨和细节理解",
    },
  },
  fallbackMatchers: [
    {
      pattern: "阅读|read|reading",
      targetModeId: "reading",
      focus: "先从短文和词汇理解入手，再做段落复述与问题回答。",
      nextStep: "先让学生读出关键词，再用完整句子回答一个阅读题。",
      example: "I think the main idea is about daily routines.",
    },
    {
      pattern: "发音|pronunciation|跟读|repeat",
      targetModeId: "pronunciation",
      focus: "先看标准示范，再做音节、重音和语调纠正。",
      nextStep: "先跟读标准句，再把重音和尾音再练一遍。",
      example: "Could you repeat that more slowly?",
    },
    {
      pattern: "口语|说|speak|speaking|问答",
      targetModeId: "dialogue",
      focus: "先给学生一个完整回答框架，再让他用自己的话说出来。",
      nextStep: "把问题拆成开头句、核心句和结尾句来练。",
      example: "My favorite subject is English because I can talk with people.",
    },
    {
      pattern: "写作|writing|作文",
      targetModeId: "essay",
      focus: "先给写作结构，再补词汇和连接词，最后检查完整性。",
      nextStep: "先写三句，再扩成一段，最后润色表达。",
      example: "First, I describe the topic. Then, I add examples. Finally, I conclude.",
    },
    {
      pattern: "教材|school|学校|同步",
      targetModeId: "plain-text",
      focus: "先和学校教材对齐，再把课内词汇和课后练习串起来。",
      nextStep: "先确认课本单元，再给学生一个同步练习。",
      example: "This unit focuses on classroom language and daily interaction.",
    },
  ],
});
