window.IvyTutorBoot({
  tutorName: "IvyEuro AI 数学老师",
  knowledgeBaseUrl: "data/math-knowledge-base.json",
  fallbackKnowledgeBase: {
    tutor: {
      name: "IvyEuro AI Math Tutor",
      role: "先检索知识库，再组织成讲题、拆题、纠错和追问练习的答案。",
      principles: [
        "先找来源，再生成回答",
        "优先使用可拆解、可复练的步骤",
        "根据年级和水平调整讲法",
        "回答后给出下一步练习",
      ],
    },
    sources: [
      { id: "plain-text", name: "Plain text", summary: "可直接导入讲义、题目、练习文本和课堂纠错记录。", focus: "自定义内容、课堂文本、练习材料", keywords: ["自定义", "讲义", "练习", "文本", "纠错", "课堂", "题目", "步骤"] },
      { id: "textbook", name: "数学教材", summary: "适合学校同步、基础巩固和分阶段训练。", focus: "课内同步、基础巩固、阶段训练", keywords: ["教材", "同步", "数学", "计算", "方程", "几何", "应用题"] },
      { id: "problem-bank", name: "题库", summary: "适合应用题、分层题和能力题训练。", focus: "应用题、分层题、能力题", keywords: ["题库", "应用题", "分层", "能力题", "练习", "题目"] },
      { id: "error-book", name: "错题本", summary: "适合错因分析、步骤修复和回练素材。", focus: "错因分析、步骤修复、回练", keywords: ["错题", "错因", "复练", "回练", "步骤", "错误"] },
      { id: "explanations", name: "讲题范例", summary: "适合解题步骤、表达方式和示范过程。", focus: "解题步骤、表达方式、示范过程", keywords: ["讲题", "示范", "步骤", "解法", "过程", "讲解"] },
    ],
    modes: [
      { id: "plain-text", label: "Plain text", title: "导入文本", summary: "把讲义、题目和练习变成可直接讲解的内容。", promptHint: "适合上传讲义、题目、练习或自定义文本。", preferredSources: ["plain-text"], sampleQuestions: ["把这道题整理成课堂要点", "把这份练习变成三步练习", "把这段讲义总结成 5 个重点"], outputStyle: "摘要 + 可讲解要点 + 下一步" },
      { id: "dialogue", label: "对话", title: "解题问答", summary: "围绕审题、思路和追问进行问答与解释。", promptHint: "适合练习口头讲题和完整思路输出。", preferredSources: ["textbook", "plain-text"], sampleQuestions: ["请和学生做一个解题问答", "请模拟老师和学生讲这道题", "请练习一个方程追问"], outputStyle: "对白 + 追问 + 复述" },
      { id: "correction", label: "纠错", title: "步骤纠错", summary: "把学生输入修正成更完整、更准确的数学步骤。", promptHint: "适合批改步骤、找逻辑问题、改计算错误。", preferredSources: ["error-book", "plain-text"], sampleQuestions: ["这道题步骤有问题，帮我纠正", "我的列式错了，帮我改", "这一步写错了，帮我解释"], outputStyle: "原步骤 + 修改步骤 + 错误说明" },
      { id: "pronunciation", label: "讲解", title: "讲题示范", summary: "聚焦讲题节奏、步骤顺序和表达清晰度。", promptHint: "适合练讲题、口头表达和步骤顺序。", preferredSources: ["explanations", "textbook"], sampleQuestions: ["请示范这道方程的讲题步骤", "我想练这道应用题的表达", "请帮我检查讲题顺序"], outputStyle: "步骤提示 + 讲解建议 + 跟练题" },
      { id: "essay", label: "作文", title: "解题表达", summary: "从思路、结构、符号到完整解答输出。", promptHint: "适合写解题过程、总结方法和润色表达。", preferredSources: ["plain-text", "explanations"], sampleQuestions: ["写一段这道题的解题过程", "帮我把这题讲得更有逻辑", "给我一个数学证明的提纲"], outputStyle: "提纲 + 示例过程 + 连接词" },
      { id: "reading", label: "阅读", title: "应用题阅读", summary: "帮助学生抓条件、找关系、理解题目结构。", promptHint: "适合应用题理解、条件分析和结构拆解。", preferredSources: ["problem-bank", "textbook"], sampleQuestions: ["帮我分析这道应用题的条件", "这道题里有哪些关键数据", "给我一个应用题训练"], outputStyle: "条件 + 关系 + 题目" },
    ],
    demoQuestions: ["怎么帮五年级学生练应用题？", "这道题步骤有问题，帮我纠错", "给我一个方程讲题示范"],
  },
  selectors: {
    questionField: "#math-ai-question",
    answerBox: "#math-ai-answer",
    sourceRow: "#math-ai-sources",
    kbList: "#math-kb-list",
    askButton: "[data-math-ask]",
    resetButton: "[data-math-reset]",
    activeModeName: "#math-active-mode-title",
    activeModeHint: "#math-active-mode-hint",
    modeButtons: "[data-math-mode]",
    functionCards: "[data-tutor-card]",
  },
  modeAttr: "data-math-mode",
  sampleAttr: "data-math-sample",
  sampleSelector: "[data-math-sample]",
  defaultModeId: "dialogue",
  defaultQuestion: "怎么帮学生练数学？",
  defaultFocus: "先用知识库中的标准步骤示范，再让学生复练。",
  defaultNextStep: "建议先从一道简单题开始，确认步骤后再进入追问。",
  defaultExample: "3x + 5 = 20",
  defaultExtra: "你可以继续追问：请给我一个同类题。",
  sourceScoring: [
    { pattern: "应用题|题目|条件", sourceId: "problem-bank", bonus: 2 },
    { pattern: "错题|步骤|纠错", sourceId: "error-book", bonus: 2 },
    { pattern: "方程|讲题|示范|解法", sourceId: "explanations", bonus: 2 },
  ],
  modeOverrides: {
    "plain-text": {
      focus: "先把输入文本拆成题型、条件、步骤和练习任务。",
      nextStep: "先整理成三段：讲解、练习、复习。",
      example: "主题：方程；关键词：等式、变形、验算。",
      extra: "你可以继续追问：把这份讲义变成 3 个课堂任务。",
    },
    dialogue: {
      focus: "先给学生完整解题框架，再让他按步骤接话和追问。",
      nextStep: "先练两轮问答，再切换题型继续。",
      example: "A: 你先看到了什么条件？ B: 已知 3x + 5 = 20。",
      extra: "你可以继续追问：再给我一个更适合小学生的讲题问答。",
    },
    correction: {
      focus: "先展示修改后的正确步骤，再解释错因。",
      nextStep: "让学生把改正后的步骤重复写一遍，确认掌握。",
      example: "先减 5，再除以 3。",
      extra: "建议一次只改 1 步，方便学生看到前后差异。",
      modeLabelLine: "当前功能：纠错 · 已识别到一步需要纠正的内容",
    },
    pronunciation: {
      focus: "先拆分讲题顺序、关键术语和表达节奏，再提供讲解提示。",
      nextStep: "先跟读标准讲解，再把步骤放进完整题目里练。",
      example: "先减 5，再除以 3。",
      extra: "如果你讲得慢一点，系统会先示范，再让你复讲。",
      modeLabelLine: "当前功能：讲解 · 优先做讲题示范",
    },
    essay: {
      focus: "先给解题提纲，再补关键步骤和示范过程。",
      nextStep: "先写三步，再扩成完整过程，再做润色。",
      example: "步骤：读题 / 列式 / 计算 / 验算。",
      extra: "你可以继续追问：帮我把这一段写得更像标准答案。",
    },
    reading: {
      focus: "先抓条件和关系，再做应用题结构拆解。",
      nextStep: "先读题目和关键数据，再回答 3 个理解问题。",
      example: "条件：已知总价和单价；要求：求数量。",
      extra: "阅读模式会优先给条件、关系和题目框架。",
      modeLabelLine: "当前功能：阅读 · 优先做应用题阅读",
    },
  },
  fallbackMatchers: [
    {
      pattern: "应用题|题目|条件",
      targetModeId: "reading",
      focus: "先从条件和关系入手，再做步骤拆解与答案验证。",
      nextStep: "先让学生找关键词，再用完整步骤回答。",
      example: "已知 3x + 5 = 20，先减 5 再除以 3。",
    },
    {
      pattern: "错题|步骤|纠错",
      targetModeId: "correction",
      focus: "先纠正错误步骤，再解释为什么这样改。",
      nextStep: "先把错因说清楚，再让学生重写一遍。",
      example: "先减 5，再除以 3。",
    },
    {
      pattern: "方程|讲题|示范|解法",
      targetModeId: "pronunciation",
      focus: "先按标准讲题顺序示范，再让学生复讲。",
      nextStep: "先讲题，再复述，再追问同类题。",
      example: "先移项，再合并同类项，最后验算。",
    },
    {
      pattern: "教材|学校|同步",
      targetModeId: "plain-text",
      focus: "先和学校教材对齐，再把题目步骤和课后练习串起来。",
      nextStep: "先确认课本单元，再给学生一个同步练习。",
      example: "这一课重点是列式、计算和验算。",
    },
  ],
});
